export const projects = [
  {
    title: 'Blog Site',
    description: "This is a project for blog site created using SpringBoot for backend, MySQL database following Spring-MVC architecture.",
    image: '/images/blog.jpg',
    tags: ['SpringBoot', 'Spring-Security', 'MySQL', 'JWT', 'JPA'],
    source: 'https://github.com/sthsuyash/Blog-Site',
    visit: 'https://github.com/sthsuyash/Blog-Site',
    id: 0,
  },
  {
    title: 'CSIT Labs',
    description: "Contains all lab codes for CSIT students for all semesters.",
    image: '/images/csit_labs.jpg',
    tags: ['C', 'C++', 'Assembly'],
    source: 'https://github.com/sthsuyash/CSIT_Labs',
    visit: 'https://github.com/sthsuyash/CSIT_Labs',
    id: 1,
  },
  {
    title: 'Python Mini Projects',
    description: "Projects using Python.",
    image: '',
    tags: ['Python'],
    source: 'https://github.com/sthsuyash/Python_mini_projects',
    visit: 'https://github.com/sthsuyash/Python_mini_projects',
    id: 2,
  },
  {
    title: 'Logistic Regression Model',
    description: "Model for logistic regression.",
    image: '',
    tags: ['Python', 'Jupyter Notebook', 'Machine Learning'],
    source: 'https://github.com/sthsuyash/Logistic_Regression-ML',
    visit: 'https://github.com/sthsuyash/Logistic_Regression-ML',
    id: 3,
  },
  {
    title: 'NewsLetter Signup',
    description: "Made by nodeJS for api practice by simple News letter subscription app.",
    image: '/images/newsletter.jpg',
    tags: ['HTML', 'CSS', 'JavaScript', 'NodeJS', 'Express'],
    source: 'https://github.com/sthsuyash/NewsLetter-Signup',
    visit: 'https://github.com/sthsuyash/NewsLetter-Signup',
    id: 4,
  },
  {
    title: 'To-Do List',
    description: "Basic todo list using React.js for learning, stores information using local storage and uses useState and useEffect Hooks",
    image: '/images/todo.jpg',
    tags: ['ReactJS', 'SCSS', 'HTML'],
    source: 'https://github.com/sthsuyash/Todo-List',
    visit: 'https://sthsuyash.github.io/Todo-List/',
    id: 5,
  },
  {
    title: 'Anythink Market',
    description: "Real life scenario project based practice from Wilco.",
    image: '/images/anythink-market.jpg',
    tags: ['JavaScript', 'NodeJS', 'ReactJS', 'HTML', 'SCSS'],
    source: 'https://github.com/ObelusFamily/Anythink-Market-6m9j7lqi',
    visit: 'https://github.com/ObelusFamily/Anythink-Market-6m9j7lqi',
    id: 6,
  },
  {
    title: 'Chat Us',
    description: "Chat Us is a real-time chat application built using React.js and SpringBoot",
    image: '/images/chatus.jpg',
    tags: ['React', 'SpringBoot', 'Spring-MVC', 'WebSocket'],
    source: 'https://github.com/sthsuyash/Chat-Us',
    visit: 'https://github.com/sthsuyash/Chat-Us',
    id: 7,
  },
];

export const TimeLineData = [
  { year: '2021/02', text: 'Started my self taught developer journey', },
  { year: '2021', text: 'Started bachelors degree in Computer Science and Information Technology', },
  { year: '2021/05', text: 'Self taught Python fundamentals', },
  { year: '2021/11', text: 'Studied C/C++ as per university guidelines', },
  { year: '2022/01', text: 'Started Web Development learning plain HTML, CSS and JavaScript', },
  { year: '2022/05', text: 'Started working as Intern in Kiko Solutions', },
  { year: '2022', text: 'Learnt basic ReactJS', },
  { year: '2022', text: 'Learnt Java SpringBoot for backend along with databases MySQL and PostgreSQL', },
  { year: '2022/11', text: 'Completed Internship at Kiko Solutions', },
  { year: '2023/02', text: 'Started Machine Learning', },
  // { year: '2023', text: '', },
  // { year: '2025', text: 'Completed bachelors degree', },
];
